// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xokfvrwlknoqmysdxicb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhva2Z2cndsa25vcW15c2R4aWNiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc4NTM2NzcsImV4cCI6MjA3MzQyOTY3N30.Czz5t_Z2Nomr_Zpcf4e4GJ4BIFMOFLVTLQKRrVkZ0mA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});